wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.2
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      4: 3.9.2
      5: 0.10.21
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: gru
batch_size:
  desc: null
  value: 74
currency:
  desc: null
  value: eur
dropout_p:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 5
layer_units:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.0611815936760807
loss:
  desc: null
  value: mean_squared_error
optimizer:
  desc: null
  value: adam
scaler_range:
  desc: null
  value:
  - 0
  - 1
