wandb_version: 1

architecture:
  value: lstm
batch_size:
  value: 122
currency:
  value: usd
dropout_p:
  value: 0.4
epochs:
  value: 5
layer_units:
  value: 16
learning_rate:
  value: 0.022536483148905263
loss:
  value: mean_squared_error
optimizer:
  value: sgd
scaler_range:
  value:
  - 0
  - 1
