wandb_version: 1

dropout:
  value: 0
epochs:
  value: 50000
features:
  value: 15
fp_emax:
  value: 72
fp_explim:
  value: CPFLOAT_EXPRANGE_TARG
fp_flip:
  value: CPFLOAT_NO_SOFTERR
fp_p:
  value: 0.04429338447672693
fp_precision:
  value: 8
fp_round:
  value: CPFLOAT_RND_SP
fp_subnormal:
  value: CPFLOAT_SUBN_USE
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum_coefficient:
  value: 0
non_negative:
  value: 1
weight_decay:
  value: 0.0001
