wandb_version: 1

dropout:
  value: 0
epochs:
  value: 50000
features:
  value: 15
fp_emax:
  value: 98
fp_explim:
  value: CPFLOAT_EXPRANGE_STOR
fp_flip:
  value: CPFLOAT_SOFTERR
fp_p:
  value: 0.20162983666056392
fp_precision:
  value: 24
fp_round:
  value: CPFLOAT_RND_NZ
fp_subnormal:
  value: CPFLOAT_SUBN_USE
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum_coefficient:
  value: 0
non_negative:
  value: 1
weight_decay:
  value: 0.0001
