wandb_version: 1

dropout:
  value: 0
epochs:
  value: 50000
features:
  value: 25
fp_emax:
  value: 121
fp_explim:
  value: CPFLOAT_EXPRANGE_STOR
fp_flip:
  value: CPFLOAT_SOFTERR
fp_p:
  value: 0.47829756253038225
fp_precision:
  value: 6
fp_round:
  value: CPFLOAT_NO_RND
fp_subnormal:
  value: CPFLOAT_SUBN_RND
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum_coefficient:
  value: 0
non_negative:
  value: 1
weight_decay:
  value: 0.0001
