wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      4: 3.9.2
      5: 0.10.21
      8:
      - 3
      - 5
dropout:
  desc: null
  value: 0
epochs:
  desc: null
  value: 50000
features:
  desc: null
  value: 25
fp_emax:
  desc: null
  value: 48
fp_explim:
  desc: null
  value: CPFLOAT_EXPRANGE_TARG
fp_flip:
  desc: null
  value: CPFLOAT_NO_SOFTERR
fp_p:
  desc: null
  value: 0.3005378690279299
fp_precision:
  desc: null
  value: 23
fp_round:
  desc: null
  value: CPFLOAT_RND_NZ
fp_subnormal:
  desc: null
  value: CPFLOAT_SUBN_USE
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: mean_squared_error
momentum_coefficient:
  desc: null
  value: 0
non_negative:
  desc: null
  value: 1
weight_decay:
  desc: null
  value: 0.0001
