wandb_version: 1

architecture:
  value: gru
batch_size:
  value: 178
currency:
  value: eur
dropout_p:
  value: 0.4
epochs:
  value: 5
layer_units:
  value: 64
learning_rate:
  value: 0.05490385576082795
loss:
  value: mean_squared_error
optimizer:
  value: rmsprop
scaler_range:
  value:
  - 0
  - 1
