wandb_version: 1

architecture:
  value: lstm
batch_size:
  value: 73
currency:
  value: usd
dropout_p:
  value: 0.5
epochs:
  value: 5
layer_units:
  value: 64
learning_rate:
  value: 0.06869554912046541
loss:
  value: mean_squared_error
optimizer:
  value: adam
scaler_range:
  value:
  - 0
  - 1
