wandb_version: 1

architecture:
  value: gru
batch_size:
  value: 68
currency:
  value: usd
dropout_p:
  value: 0.5
epochs:
  value: 5
layer_units:
  value: 16
learning_rate:
  value: 0.021762262857844085
loss:
  value: mean_squared_error
optimizer:
  value: sgd
scaler_range:
  value:
  - 0
  - 1
