wandb_version: 1

architecture:
  value: lstm
batch_size:
  value: 75
currency:
  value: eur
dropout_p:
  value: 0.3
epochs:
  value: 5
layer_units:
  value: 32
learning_rate:
  value: 0.05807313148877428
loss:
  value: mean_squared_error
optimizer:
  value: adam
scaler_range:
  value:
  - 0
  - 1
