wandb_version: 1

architecture:
  value: gru
batch_size:
  value: 74
currency:
  value: usd
dropout_p:
  value: 0.5
epochs:
  value: 5
layer_units:
  value: 16
learning_rate:
  value: 0.09824180505055624
loss:
  value: mean_squared_error
optimizer:
  value: adam
scaler_range:
  value:
  - 0
  - 1
