wandb_version: 1

architecture:
  value: lstm
batch_size:
  value: 110
currency:
  value: eur
dropout_p:
  value: 0.5
epochs:
  value: 5
layer_units:
  value: 32
learning_rate:
  value: 0.017647466442378967
loss:
  value: mean_squared_error
optimizer:
  value: rmsprop
scaler_range:
  value:
  - 0
  - 1
