wandb_version: 1

architecture:
  value: lstm
batch_size:
  value: 42
currency:
  value: eur
dropout_p:
  value: 0.5
epochs:
  value: 5
layer_units:
  value: 16
learning_rate:
  value: 0.006897791745140359
loss:
  value: mean_squared_error
optimizer:
  value: sgd
scaler_range:
  value:
  - 0
  - 1
