wandb_version: 1

architecture:
  value: lstm
batch_size:
  value: 139
currency:
  value: usd
dropout_p:
  value: 0.4
epochs:
  value: 5
layer_units:
  value: 64
learning_rate:
  value: 0.03250944481468842
loss:
  value: mean_squared_error
optimizer:
  value: rmsprop
scaler_range:
  value:
  - 0
  - 1
