wandb_version: 1

architecture:
  value: gru
batch_size:
  value: 39
currency:
  value: eur
dropout_p:
  value: 0.5
epochs:
  value: 5
layer_units:
  value: 64
learning_rate:
  value: 0.09847616944506209
loss:
  value: mean_squared_error
optimizer:
  value: sgd
scaler_range:
  value:
  - 0
  - 1
